apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume
  labels:
    app: data-store
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    emptyDir: {}
