apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env-vars
  labels:
    app: env-demo
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    env:
    - name: DB_HOST
      value: "db.example.com"
    - name: DB_PORT
      value: "5432"
    - name: APP_MODE
      value: "production"
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: secret-key
