apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multiple-volumes
spec:
  containers:
  - name: app
    image: myapp:1.0
    volumeMounts:
    # EmptyDir volume
    - name: cache-volume
      mountPath: /cache
    
    # ConfigMap volume
    - name: config-volume
      mountPath: /etc/config
    
    # Secret volume
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
    
    # HostPath volume
    - name: log-volume
      mountPath: /var/log/app
    
    # PersistentVolumeClaim
    - name: data-volume
      mountPath: /data
  
  volumes:
  # EmptyDir - temporary directory that shares a pod's lifetime
  - name: cache-volume
    emptyDir: {}
  
  # ConfigMap - for configuration data
  - name: config-volume
    configMap:
      name: app-config
  
  # Secret - for sensitive data
  - name: secret-volume
    secret:
      secretName: app-secrets
  
  # HostPath - mounts from the host node's filesystem
  - name: log-volume
    hostPath:
      path: /var/log
      type: Directory
  
  # PersistentVolumeClaim - for persistent storage
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-example
