apiVersion: v1
kind: Pod
metadata:
  name: pod-with-persistent-volume
spec:
  containers:
  - name: database
    image: postgres:14
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
    env:
    - name: POSTGRES_PASSWORD
      value: password
  volumes:
  - name: postgres-data
    persistentVolumeClaim:
      claimName: pvc-example
