apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: wordpress
spec:
  storageClassName: "local-path" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: wordpress
data:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: wordpress
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dVYxODUw
  MYSQL_PASSWORD: dVYxODUw

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: wordpress
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6.4-focal
        ports:
          - containerPort: 3306
          - containerPort: 33060
        envFrom:
          - configMapRef:
              name: db-config
          - secretRef:
              name: db-secret
        volumeMounts:
          - name: db-pvc
            mountPath: /var/lib/mysql
      volumes:
        - name: db-pvc
          persistentVolumeClaim:
            claimName: db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  namespace: wordpress
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
