apiVersion: v1
kind: Service
metadata:
  name: nginx-service-with-session-affinity
spec:
  selector:
    app: nginx
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
