apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secrets
spec:
  containers:
  - name: app
    image: myapp:1.0
    ports:
    - containerPort: 8080
    # Mount secrets as volume
    volumeMounts:
    - name: secrets-volume
      mountPath: /etc/secrets
      readOnly: true
    # Use secrets as environment variables
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: password
    # Load all Secret keys as environment variables
    envFrom:
    - secretRef:
        name: app-secrets
  volumes:
  - name: secrets-volume
    secret:
      secretName: app-secrets
