apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values
  username: YWRtaW4= # admin
  password: c3VwZXJzZWNyZXQ= # supersecret
  api-key: WFlaLTEyMy1BQkMtNDU2 # XYZ-123-ABC-456
