apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset-with-nodeselector
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        disktype: ssd
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
