apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset-with-matchexpressions
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - nginx
      - nginx-web
    - key: environment
      operator: NotIn
      values:
      - testing
  template:
    metadata:
      labels:
        app: nginx
        environment: production
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
